Better validation error when required metadata not found
Instead of just showing the error which is the name of the metadata
that's missing, include information about the page so we know which page
caused this error.  For example:

```
cnxepub ERROR Error when parsing metadata for composite-page (id: None, parent: "1 What is Physics?")
Traceback (most recent call last):
  File "/code/venv/lib/python3.6/site-packages/cnxepub/adapters.py", line 473, in _adapt_single_html_tree
    child.xpath('./*[@data-type="metadata"]')[0])
  File "/code/venv/lib/python3.6/site-packages/cnxepub/html_parsers.py", line 74, in parse_metadata
    return parser()
  File "/code/venv/lib/python3.6/site-packages/cnxepub/html_parsers.py", line 108, in __call__
    return self.metadata
  File "/code/venv/lib/python3.6/site-packages/cnxepub/html_parsers.py", line 128, in metadata
    "A value for '{}' could not be found.".format(key))
ValueError: A value for 'title' could not be found.
```