Fix 'get' command message when content exists but completezip does not
```
> neb get dev col11629
Traceback (most recent call last):
  File "/Users/pumazi/.environments/c/bin/neb", line 11, in <module>
    load_entry_point('nebuchadnezzar', 'console_scripts', 'neb')()
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/pumazi/cnx/src/nebuchadnezzar/nebu/cli/main.py", line 163, in get
    content_size = int(resp.headers['Content-Length'].strip())
  File "/Users/pumazi/.environments/c/lib/python3.5/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

This now returns a message instead:

```
> neb get dev col11629
The content exists, but the completezip is missing
Error: content unavailable for 'col11629/latest'
```