patch the ToC file to include a hidden reference to the cover page, f… (#284)
* patch the ToC file to include a hidden reference to the cover page, fixes #2084

* move the hidden ol inside the first li

* fix node segmentation fault on manual run

* move toc cover patching logic to another place

* remove empty spans

* encapsulate hidden ol further in an li

* Revert "remove empty spans"

This reverts commit d5a8831c5c343a188df9022cc935ff3a0499bcc2.

* change hidden ol to nav landmarks

* add missing epub namespace to cover xhtml

* update snapshot tests

* clean up

* fix JQ release key changes

* use minidom for creating the nav landmarks

* update snapshot

* fix flake8 in bakery

new flake8 6.1 reported this error:
cnx_models.py:352:5: F811 redefinition of unused 'ident_hash' from line 335